### ISSUE TITLE
Firefox And Chrome profile (fileSystem restricted)

### ISSUE THREAD

**Issue by alidehghan** [valoq/bwscripts#6]
I need two profiles for firefox and chrome to restrict all FileSystems to specified directory. To put it simple, I am going to add a user, and make a directory and set permissions on that, and I need to run firefox (and chrome) under those permissions. When browsers started and some websites loaded, user wants to download the image or html or everything, I need to restrict browser dialog into just that directory I specified, (Home, Desktop and other places should be inaccessible and not displaying).

Is that possible?

**Comment by valoq** [comment]
Not quite sure what you intent to do. If your question is in regard to bubblewrap and if it is possible to permit downloads into you specified directory, then all you need is a bind mount to that path.
Regarding the dialog, it is also possible to make the browsers download default into a specific path, though that is outside the scope of this project and you would have to look up the documentation for firefox and chromium or the specific desktop environment in question. Though the user will still be able to chose a different path manually just like they can browse the entire filesystem that is visible to the process. If you objective is to restrict what the user can access, the bubblewrap scripts are the way to go. The download dialog wont implement any effective restrictions.

**Comment by alidehghan** [comment]
Thanks for your reply, What I actually is looking for it restricting download dialog for user. (for practice, open a webpage and right click on the page and choose Save As ..., dialog which is prompted is the main challenge). My Users are using ubuntu as client os, so they can navigate all system through that dialog window

**Comment by valoq** [comment]
You can use bubblewrap to restrict the access of the entire process, however there is no effective way to restrict the download dialog that I know of. There may be some gui option to configure the dialog but that is outside the scope of this project.
