### ISSUE TITLE
bwrap: execvp /opt/dir/whatever: No such file or directory

### ISSUE THREAD

**Issue by commonuserlol** [valoq/bwscripts#7]
Hi, sorry for noob question, but as title says I have this error. Script:
```bash
#!/usr/bin/env bash
set -euo pipefail
(
    exec bwrap \
     --ro-bind /usr/bin /usr/bin/ \
     --ro-bind /usr/share /usr/share \
     --ro-bind /usr/lib /usr/lib \
     --ro-bind /usr/lib64 /usr/lib64 \
     --symlink /usr/lib64 /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     --ro-bind /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" /run/user/"$(id -u)"/"$WAYLAND_DISPLAY" \
     --proc /proc \
     --dev /dev \
     --bind "$PWD" "$PWD" \
     --unshare-all \
     --new-session \
     --seccomp 10 \
     10< /usr/local/bin/seccomp_default_filter.bpf \
     "/opt/dit/whatever" "$@"
)

```
`/opt/dir/whatever` is exists and have `-rwxr-xr-x` perms, ownership is `commonuserlol:root`

**Comment by valoq** [comment]
The path in your example is `/opt/dit/whatever` and not `/opt/dir/whatever`
Could that be the issue?

**Comment by commonuserlol** [comment]
With --ro-bind option I've got `error while loading shared libraries: libwhatever.so: cannot open shared object file: No such file or directory`. Should I add /opt/dir to path or use `--ro-bind /opt/dir /opt/dir`?

> Also, your example uses /opt/dit/whatever and not /opt/dir/whatever

It's my stupid mistake when I was changing name

**Comment by valoq** [comment]
You add the required file with --ro-bind /opt/dir /opt/dir to have it available in your runtime environment.
That should fix the error
